spring:
  application:
    name: catalog-service

  kafka:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

  datasource:
    primary:
      jdbc-url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/catalog_db}
      username: ${SPRING_DATASOURCE_USERNAME:postgres}
      password: ${SPRING_DATASOURCE_PASSWORD:password}
      driver-class-name: org.postgresql.Driver

    replica:
      jdbc-url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/catalog_db}
      username: ${SPRING_DATASOURCE_USERNAME:postgres}
      password: ${SPRING_DATASOURCE_PASSWORD:password}
      driver-class-name: org.postgresql.Driver

kafka:
  topic:
    upload: ${KAFKA_TOPIC_VIDEO_UPLOADED:xtube.video.progress}
    processing: ${KAFKA_TOPIC_VIDEO_PROCESSING:xtube.video.progress}

cloudfront:
  resource-url: ${CLOUDFRONT_URL:example.com}
  private-key: ${CLOUDFRONT_PRIVATE_KEY:private-key-example.pem}
  key-pair-id: ${CLOUDFRONT_KEY_ID:123}

server:
  domain: "api.xtube.com"